(ns uml-viewer.application.ir-generator
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [uml-viewer.graph :as graph]
            [uml-viewer.domain.policy :as policy]))

(defn read-policy [path]
  (edn/read-string (slurp path)))

(defn emit [doc]
  (str ";; Generated by clj -M:ir from the policy file. Do not edit.\n"
       (binding [*print-namespace-maps* false
                 *print-length* nil
                 *print-level* nil
                 pprint/*print-right-margin* 90]
         (with-out-str (pprint/pprint doc)))))

(defn document
  "Scan source with `graph-impl` and apply `policy`. Returns the IR document."
  [graph-impl policy]
  (let [root (or (:src policy) "src")
        opts {:prefix (or (:prefix policy) "uml-viewer")}
        graph (graph/scan graph-impl root opts)]
    (policy/apply-policy policy graph)))

(defn generate
  "Write the IR document for `policy-path` using `graph-impl`. Returns the output path."
  ([graph-impl policy-path] (generate graph-impl policy-path nil))
  ([graph-impl policy-path out-path]
   (let [policy (read-policy policy-path)
         graph (graph/scan graph-impl
                           (or (:src policy) "src")
                           {:prefix (or (:prefix policy) "uml-viewer")})
         extra (policy/unassigned policy graph)
         doc (merge (policy/apply-policy policy graph)
                    (select-keys graph [:lang :source-root :source-prefix :metrics-mode])
                    {:policy-file policy-path})
         out (or out-path (:out policy) "examples/uml-viewer.edn")]
     (when (seq extra)
       (binding [*out* *err*]
         (println "Unassigned namespaces:"
                  (str/join ", " (map :ns extra)))))
     (io/make-parents out)
     (spit out (emit doc))
     out)))
