(ns uml-viewer.application.ir-generator
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [uml-viewer.application.metrics :as metrics]
            [uml-viewer.graph :as graph]
            [uml-viewer.domain.policy :as policy]))

(defn read-policy [path]
  (edn/read-string (slurp path)))

(defn emit [doc]
  (str ";; Generated by clj -M:ir from the policy file. Do not edit.\n"
       (binding [*print-namespace-maps* false
                 *print-length* nil
                 *print-level* nil
                 pprint/*print-right-margin* 90]
         (with-out-str (pprint/pprint doc)))))

(defn- annotate
  "The viewer reads `:lang` and `:src` off the IR to open the right file.
   Language graphs that report them (Python) win; the policy fills the rest."
  [doc policy graph]
  (merge doc
         (select-keys graph [:lang :source-root :source-prefix :metrics-mode])
         (cond-> {:src (or (:src policy) "src")}
           (:lang policy) (assoc :lang (keyword (:lang policy))))))

(defn- build
  "Scan and apply policy. `:members` is present for languages that report them."
  [graph-impl policy]
  (let [root (or (:src policy) "src")
        opts {:prefix (or (:prefix policy) "uml-viewer")}
        graph (graph/scan graph-impl root opts)]
    {:graph graph
     :doc (annotate (policy/apply-policy policy graph) policy graph)}))

(defn document
  "Scan source with `graph-impl` and apply `policy`. Returns the IR document."
  [graph-impl policy]
  (:doc (build graph-impl policy)))

(defn generate
  "Write the IR document for `policy-path` using `graph-impl`. Returns the output path.
   `opts` may include `:metrics-root` (default user.dir) for the static member snapshot."
  ([graph-impl policy-path] (generate graph-impl policy-path nil))
  ([graph-impl policy-path out-path] (generate graph-impl policy-path out-path {}))
  ([graph-impl policy-path out-path opts]
   (let [policy (read-policy policy-path)
         {:keys [graph doc]} (build graph-impl policy)
         extra (policy/unassigned policy graph)
         doc (assoc doc :policy-file policy-path)
         out (or out-path (:out policy) "examples/uml-viewer.edn")
         members (:members graph)]
     (when (seq extra)
       (binding [*out* *err*]
         (println "Unassigned namespaces:"
                  (str/join ", " (map :ns extra)))))
     (when (seq members)
       (metrics/write-static! (or (:metrics-root opts)
                                  (System/getProperty "user.dir"))
                              members))
     (io/make-parents out)
     (spit out (emit doc))
     out)))
